apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmkweb
  labels:
    app: bmkweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bmkweb
  template:
    metadata:
      labels:
        app: bmkweb
    spec:
      containers:
      - name: php-apache
        image: yenaing/php72
        ports:
        - containerPort: 80
        volumeMounts:
        - name: hostvol
          mountPath: /var/www/html/
      volumes:
        - name: hostvol
          persistentVolumeClaim:
            # PVC name you created
            claimName: bmkweb-pvc
