apiVersion: apps/v1
kind: Deployment
metadata:
  name: chitweb
  labels:
    app: chitweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chitweb
  template:
    metadata:
      labels:
        app: chitweb
    spec:
      containers:
      - name: php-apache
        image: yenaing/php72
        ports:
        - containerPort: 80
        volumeMounts:
        - name: hostvol
          mountPath: /var/www/html/
      volumes:
        - name: hostvol
          persistentVolumeClaim:
            # PVC name you created
            claimName: chitweb-pvc
